import NavBar from "@/components/NavBar";
import "./globals.css";
import { ThemeProvider } from "@/components/ThemeProvider";
import Spacer from "@/components/Spacer";

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body>
        <main className="min-h-screen bg-background flex flex-col items-center">
          <ThemeProvider attribute="class" defaultTheme="system" enableSystem>
            <NavBar />
            <Spacer />
            {children}
          </ThemeProvider>
        </main>
      </body>
    </html>
  );
}
